# TRACE -> GUARD role-play video: slide layouts (1920x1080).
# Card types map to marker colors: narration=sky, interviewer=slate, think=amber,
# say=teal, nugget=purple, data=neutral, alert=red.

def card(x, y, w, h, type, kicker, title, lines=None):
    return dict(x=x, y=y, w=w, h=h, type=type, kicker=kicker, title=title, lines=lines or [])

SLIDES = {
    "title": dict(kicker="ROLE-PLAY LESSON", title="TRACE → GUARD", num=1, cards=dict(
        t1=card(310, 190, 1300, 330, "narration", "THE FRAMEWORK",
                "Diagnose the incident. Design the guard.",
                ["Part One · something is broken in production — find the root cause",
                 "Part Two · design the system that handles the whole failure class",
                 "Built for the incident half of the system-design interview"]),
        t2=card(460, 580, 1000, 340, "interviewer", "THE CAST",
                "Two voices, three layers",
                ["Dan · the narrator — and you, the candidate",
                 "Rachel · the interviewer — and every nugget",
                 "Each scene: what they say · what you think · what you say"]),
    )),

    "halves": dict(kicker="ORIENTATION", title="The interview has two connected halves", num=2, cards=dict(
        h1=card(70, 190, 880, 390, "data", "PART ONE", "TRACE the incident",
                ["Something is broken in production",
                 "Identify the failing decision",
                 "Explain the mechanism",
                 "Connect the cause to the timing"]),
        h2=card(990, 190, 860, 390, "data", "PART TWO", "GUARD the system",
                ["Design for the broader failure class",
                 "Requirements and red lines",
                 "Prevention · detection · recovery",
                 "Roll out safely and monitor"]),
        hf=card(70, 630, 1080, 300, "narration", "THE MOVE", "Trace first. Then guard.",
                ["One continuous argument:",
                 "symptom → root cause → durable system"]),
        hn=card(1190, 630, 660, 300, "nugget", "NUGGET 1", "Never design before you diagnose",
                ["Trace the incident first.",
                 "Then guard the system."]),
    )),

    "trace": dict(kicker="PART ONE", title="TRACE · five moves from ambiguity to cause", num=3, cards=dict(
        tr_t=card(70, 200, 340, 470, "narration", "T", "Translate",
                  ["Expected vs observed", "Metric · onset · severity", "Sanity-check the signal"]),
        tr_r=card(430, 200, 340, 470, "narration", "R", "Restrict",
                  ["Affected vs unaffected", "Smallest predicting", "condition"]),
        tr_a=card(790, 200, 340, 470, "narration", "A", "Aim",
                  ["5–8 stages", "Start where evidence", "points — say why"]),
        tr_c=card(1150, 200, 340, 470, "narration", "C", "Compare",
                  ["Affected vs healthy", "Earliest divergence", "Exact input / output"]),
        tr_e=card(1510, 200, 340, 470, "narration", "E", "Establish",
                  ["One-variable test", "Mechanism + timing", "Then stop"]),
        tr_n=card(340, 720, 1240, 240, "nugget", "NUGGET 2", "Hunt the earliest divergence",
                 ["Downstream components can be correct victims of bad upstream input."]),
    )),

    "guard": dict(kicker="PART TWO", title="GUARD · five moves from incident to system", num=4, cards=dict(
        g_g=card(70, 230, 340, 480, "narration", "G", "Generalize",
                 ["Name the broader", "failure class"]),
        g_u=card(430, 230, 340, 480, "narration", "U", "Understand",
                 ["Requirements and", "red lines"]),
        g_a=card(790, 230, 340, 480, "narration", "A", "Architect",
                 ["Prevention · detection", "· recovery"]),
        g_r=card(1150, 230, 340, 480, "narration", "R", "Reason",
                 ["Tradeoffs and", "failure modes"]),
        g_d=card(1510, 230, 340, 480, "narration", "D", "Deploy",
                 ["Evaluation · rollout", "· monitoring"]),
    )),

    "contain": dict(kicker="THE INTERRUPT", title="Contain severe harm in parallel", num=5, cards=dict(
        c1=card(70, 190, 860, 390, "alert", "WHEN", "Do not wait for a perfect diagnosis",
                ["Safety · private data · money · destructive actions",
                 "Take a reversible action that reduces exposure",
                 "Rollback · disable · safe fallback · human approval"]),
        c2=card(990, 190, 860, 390, "say", "YOU SAY", "“Containment and diagnosis in parallel”",
                ["Name the temporary action",
                 "Name its cost — latency, false refusals",
                 "Preserve the evidence for replay"]),
        c3=card(70, 620, 860, 310, "nugget", "NUGGET 3", "Diagnosis can wait. Damage cannot.",
                ["Severe harm → contain in parallel."]),
        c4=card(990, 620, 860, 310, "data", "CHEAT SHEET · GROWING", "Your first three triggers",
                ["1 · Expected? Observed? Metric? Onset?",
                 "2 · Affected vs unaffected?",
                 "3 · Severe harm? Contain in parallel."]),
    )),

    "case1_open": dict(kicker="SCENE ONE · CASE", title="The assistant that cannot find existing documents", num=6, cards=dict(
        i1=card(70, 180, 900, 440, "interviewer", "INTERVIEWER", "“Diagnose it.”",
                ["“I couldn’t find enough information” — but the",
                 "user can open the source document",
                 "Answer-with-citations 90% → 82% · since 9:40",
                 "Errors flat · latency slightly better"]),
        i2=card(1010, 180, 840, 440, "think", "YOU THINK", "Don’t touch embeddings yet",
                ["A document can die at ingest · index · retrieve ·",
                 "permission · rank · sufficiency · generate",
                 "“Source exists” proves nothing about the pipeline",
                 "Faster + worse = maybe doing less work"]),
        i3=card(70, 660, 900, 340, "say", "YOU SAY", "Translate before you hypothesize",
                ["Expected · observed · metric · onset — out loud",
                 "“Has the metric definition or logging changed?”"]),
        i4=card(1010, 660, 840, 340, "nugget", "NUGGET 4", "Source exists ≠ source reached the model",
                ["Keep the two claims separate on your board."]),
    )),

    "case1_scope": dict(kicker="SCENE ONE · RESTRICT", title="Find the smallest condition that predicts failure", num=7, cards=dict(
        b1=card(70, 180, 880, 390, "interviewer", "INTERVIEWER", "The blast radius",
                ["Google Workspace connectors · group-shared docs",
                 "Direct user grants — mostly healthy",
                 "Regions and model versions look similar"]),
        b2=card(990, 180, 860, 390, "think", "YOU THINK", "That is a boundary condition",
                ["Group-based access predicts failure",
                 "A model-wide bug wouldn’t care how docs are shared",
                 "Smells like identity · ACLs · permission enforcement"]),
        b3=card(70, 610, 880, 390, "say", "YOU SAY", "Name what got less — and more — likely",
                ["“Not global — group-based permission representation”",
                 "Broad model / retrieval regression ↓",
                 "Connector · identity · permission filtering ↑",
                 "“One affected group-grant + one healthy direct-grant”"]),
        b4=card(990, 610, 860, 390, "nugget", "NUGGET 5", "A healthy control constrains your theory",
                ["More than another failing example does."]),
    )),

    "case1_path": dict(kicker="SCENE ONE · AIM", title="The request path — circle where you start", num=8, cards=dict(
        pb1=card(70, 190, 420, 150, "data", "1", "User request", []),
        pb2=card(520, 190, 420, 150, "data", "2", "Auth + tenant context", []),
        pb3=card(970, 190, 420, 150, "data", "3", "Query processing", []),
        pb4=card(1420, 190, 420, 150, "data", "4", "Hybrid retrieval", []),
        pb5=card(70, 370, 420, 150, "alert", "5", "Permission filtering", []),
        pb6=card(520, 370, 420, 150, "data", "6", "Reranking", []),
        pb7=card(970, 370, 420, 150, "data", "7", "Evidence sufficiency", []),
        pb8=card(1420, 370, 420, 150, "data", "8", "Generation + citations", []),
        p_say=card(70, 590, 1180, 390, "say", "YOU SAY", "Start in the evidence pipeline — and say why",
                   ["Request completes · fallback is deliberate · latency ↓",
                    "That fits skipped work or disappearing candidates",
                    "Track the expected document across every stage:",
                    "present when the stage began — still there when it ended?"]),
        p_n=card(1290, 590, 560, 390, "nugget", "NUGGET 6", "Faster can mean less work",
                 ["Speed-ups are evidence too."]),
    )),

    "case1_compare": dict(kicker="SCENE ONE · COMPARE", title="Find the earliest divergence", num=9, cards=dict(
        m1=card(70, 180, 880, 390, "data", "STAGE METRICS", "The first new drop",
                ["Retrieved            190/200 → 189/200   stable",
                 "Survives permission  184/200 → 164/200   DROP",
                 "Later stages — stable given their inputs"]),
        m2=card(990, 180, 860, 390, "interviewer", "AFFECTED TRACE", "One request, stage by stage",
                ["Expected doc retrieved at rank 2",
                 "Removed: NO_MATCHING_PRINCIPAL",
                 "Sufficiency fails · generation never invoked"]),
        m3=card(70, 610, 880, 390, "think", "YOU THINK", "Downstream stages are correct victims",
                ["First divergence = permission filtering",
                 "The fork is binary now:",
                 "wrong filter logic — or wrong principals from upstream"]),
        m4=card(990, 610, 860, 390, "say", "YOU SAY", "The evidence-update loop, out loud",
                ["“This makes retrieval quality less likely…”",
                 "“…and permission inputs more likely.”",
                 "“Next: compare resolved principals vs the doc ACL.”",
                 "“Did anything roll out near 9:40?”"]),
    )),

    "case1_establish": dict(kicker="SCENE ONE · ESTABLISH", title="One controlled replay settles it", num=10, cards=dict(
        e1=card(70, 180, 580, 390, "interviewer", "THE REVEAL", "A correlated rollout",
                ["Principal canonicalization v2",
                 "0% → 100% between 9:32 and 9:40",
                 "Incident begins at 9:40"]),
        e2=card(690, 180, 560, 390, "data", "REPLAY · V1", "27 principals",
                ["Workspace group alias present",
                 "Permission ALLOW",
                 "Correct cited answer"]),
        e3=card(1290, 180, 560, 390, "alert", "REPLAY · V2", "19 principals",
                ["Group alias missing",
                 "Permission DENY",
                 "Fallback response"]),
        e4=card(70, 600, 1180, 400, "say", "YOU SAY · DIAGNOSIS", "Cause · mechanism · timing · evidence",
                ["v2 removed a group alias that document ACLs still use",
                 "Authorized users lost their matching principal",
                 "Doc removed at permission → sufficiency fails → no generation",
                 "Replay reproduces and reverses · alternative: stale ACL index"]),
        e5=card(1290, 600, 560, 400, "nugget", "NUGGET 7", "One controlled replay",
                ["beats twenty clarifying questions."]),
    )),

    "case1_guard": dict(kicker="SCENE ONE · GUARD", title="Design for the class, not the alias", num=11, cards=dict(
        ga1=card(70, 180, 560, 330, "interviewer", "INTERVIEWER", "“Now design the general system.”",
                 ["Prevent — or safely handle —",
                  "this class of failure"]),
        ga2=card(670, 180, 1180, 330, "say", "GENERALIZE + RED LINE", "Identity normalization changed authorization semantics",
                 ["Invariant: a representation-only change must never change",
                  "the effective set of authorized documents"]),
        ga3=card(70, 550, 880, 450, "say", "ARCHITECT", "Four parts",
                 ["1 · Versioned identity graph — canonical IDs + aliases",
                  "2 · Compatible serving — canonical + aliases during migration",
                  "3 · Semantic shadowing — diff old vs new decisions",
                  "4 · Recovery — flag · rollback · replay · audit logs"]),
        ga4=card(990, 550, 860, 260, "say", "TRADEOFFS + ROLLOUT", "Fail closed · gate on semantic equivalence",
                 ["Bound the cost: fast false-deny detection",
                  "Replay → shadow → canary → ramp · delta stops it"]),
        ga5=card(990, 840, 860, 160, "nugget", "NUGGET 8", "Compare decisions, not principal counts", []),
    )),

    "case2": dict(kicker="SCENE TWO", title="The multi-turn safety bypass", num=12, cards=dict(
        x1=card(70, 180, 560, 390, "interviewer", "INTERVIEWER", "Each message looks benign",
                ["Refusals bypassed across turns",
                 "Single-turn attacks still blocked",
                 "Started this afternoon"]),
        x2=card(670, 180, 560, 390, "think", "YOU THINK", "Containment interrupt — now",
                ["Severe harm.",
                 "Contain in parallel."]),
        x3=card(1290, 180, 560, 390, "say", "YOU SAY", "Contain, then translate",
                ["Route risky multi-turn convos through",
                 "the full-conversation classifier",
                 "Boundary: enforcement scope,",
                 "not model capability"]),
        x4=card(70, 610, 560, 390, "interviewer", "THE REVEAL", "Router change",
                ["Cumulative-risk check no longer",
                 "triggered — the conversation",
                 "detector was skipped"]),
        x5=card(670, 610, 560, 390, "say", "YOU SAY · GUARD", "Conversation-level risk state",
                ["A risk budget per conversation",
                 "Enforcement reads it every turn",
                 "Multi-turn attack suite gates rollouts"]),
        x6=card(1290, 610, 560, 390, "nugget", "NUGGET 9", "Match enforcement to the unit of risk",
                ["Risk accumulates across turns."]),
    )),

    "case3": dict(kicker="SCENE THREE", title="The payment that ran twice", num=13, cards=dict(
        y1=card(70, 180, 560, 390, "interviewer", "INTERVIEWER", "Charged twice · one proposal",
                ["Intermittent",
                 "Started after a “reliability",
                 "improvement” shipped"]),
        y2=card(670, 180, 560, 390, "think", "YOU THINK", "That smells like retries",
                ["One correct proposal → fault is",
                 "downstream: runtime or executor"]),
        y3=card(1290, 180, 560, 390, "say", "YOU SAY", "Name the fork before the data",
                ["“Does the executor retry on timeout?”",
                 "“Is the payment idempotent?”",
                 "Guess: success + timeout + blind retry"]),
        y4=card(70, 610, 560, 390, "interviewer", "THE REVEAL", "No idempotency key",
                ["New retry policy resends on timeout",
                 "Payment API has no stable identity"]),
        y5=card(670, 610, 560, 390, "say", "YOU SAY · GUARD", "Stable action identity",
                ["Client-generated idempotency keys",
                 "Timeout = unknown → reconcile first",
                 "Financial actions fail closed to a human"]),
        y6=card(1290, 610, 560, 390, "nugget", "NUGGET 10", "Timeout means unknown, not failed",
                ["A retry is only safe with a stable identity."]),
    )),

    "mistakes": dict(kicker="AVOID", title="Seven common mistakes", num=14, cards=dict(
        mk1=card(70, 200, 420, 360, "alert", "1", "Hypothesizing before translating", []),
        mk2=card(520, 200, 420, 360, "alert", "2", "Architecture as a memory recital", []),
        mk3=card(970, 200, 420, 360, "alert", "3", "Fifteen causes, no cohort table", []),
        mk4=card(1420, 200, 420, 360, "alert", "4", "Blaming the loudest failure", []),
        mk5=card(295, 600, 420, 360, "alert", "5", "Investigating past a decisive replay", []),
        mk6=card(745, 600, 420, 360, "alert", "6", "Patching the instance, not the class", []),
        mk7=card(1195, 600, 420, 360, "alert", "7", "Rollback restores code, not state", []),
    )),

    "stuck": dict(kicker="WHEN YOU FREEZE", title="The stuck protocol", num=15, cards=dict(
        st1=card(70, 180, 880, 280, "say", "SAY THIS FIRST", "Buy time honestly",
                 ["“Let me take a moment to update",
                  "my hypothesis from that evidence.”"]),
        st2=card(990, 180, 860, 280, "data", "THREE WORDS", "Evidence · Meaning · Next",
                 ["What did I learn? · What shifted?",
                  "· What one comparison moves me?"]),
        st3=card(70, 500, 1180, 490, "data", "FIVE RESCUE QUESTIONS", "One of these almost always works",
                 ["1 · Compare one affected vs one matched healthy request?",
                  "2 · What entered / exited the first diverging component?",
                  "3 · What changed near the onset?",
                  "4 · Can we change only the suspected variable?",
                  "5 · What single fact still blocks a diagnosis?"]),
        st4=card(1290, 500, 560, 490, "nugget", "NUGGET 11", "Questions don’t make you junior",
                 ["Questions disconnected", "from evidence do."]),
    )),

    "close": dict(kicker="CLOSE", title="One movement, one sentence", num=16, cards=dict(
        cl1=card(70, 180, 1780, 220, "narration", "THE MOVEMENT",
                 "Symptom → Scope → Path → Divergence → Decision → Evidence → Cause",
                 ["Then generalize — and harden."]),
        cl2=card(70, 440, 560, 300, "data", "CHEAT SHEET", "A trigger for every step",
                 ["Saved beside this video —",
                  "rehearse it before the interview"]),
        cl3=card(670, 440, 1180, 300, "say", "THE SENTENCE", "Say it at every piece of evidence",
                 ["“This makes one explanation less likely and another",
                  "more likely. Here is the next test that separates them.”"]),
        cl4=card(70, 780, 880, 240, "nugget", "FINAL NUGGET", "Reduce uncertainty one step at a time",
                 ["You are not solving the whole system at once."]),
        cl5=card(990, 780, 860, 240, "narration", "YOUR TURN", "Run the scenes again tomorrow",
                 ["Cover the candidate’s lines —",
                  "answer before he does."]),
    )),
}

SLIDE_ORDER = ["title", "halves", "trace", "guard", "contain", "case1_open", "case1_scope",
               "case1_path", "case1_compare", "case1_establish", "case1_guard",
               "case2", "case3", "mistakes", "stuck", "close"]
